// <auto-generated />
using System;
using EnrollmentApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnrollmentApp.Migrations
{
    [DbContext(typeof(CollegeContext))]
    [Migration("20200224064145_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EnrollmentApp.Course", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CreditHour")
                        .HasColumnType("int");

                    b.Property<float>("FeeAmount")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgramName")
                        .HasColumnType("int");

                    b.Property<int?>("ProgramsProgramName")
                        .HasColumnType("int");

                    b.Property<int>("Semisterbatch")
                        .HasColumnType("int");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("semisterName")
                        .HasColumnType("int");

                    b.HasKey("Code")
                        .HasName("Pk_CourseCode");

                    b.HasIndex("ProgramName");

                    b.HasIndex("ProgramsProgramName");

                    b.HasIndex("StudentId");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("EnrollmentApp.Programs", b =>
                {
                    b.Property<int>("ProgramName")
                        .HasColumnType("int");

                    b.HasKey("ProgramName")
                        .HasName("Pk_ProgramName");

                    b.ToTable("programs");
                });

            modelBuilder.Entity("EnrollmentApp.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfEnrollement")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgramNames")
                        .HasColumnType("int");

                    b.Property<int?>("ProgramsProgramName")
                        .HasColumnType("int");

                    b.Property<int>("Sex")
                        .HasColumnType("int")
                        .HasMaxLength(1);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("courseCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("Pk_StudentId");

                    b.HasIndex("ProgramNames");

                    b.HasIndex("ProgramsProgramName");

                    b.HasIndex("courseCode");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EnrollmentApp.Course", b =>
                {
                    b.HasOne("EnrollmentApp.Programs", "program")
                        .WithMany()
                        .HasForeignKey("ProgramName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnrollmentApp.Programs", null)
                        .WithMany("Courses")
                        .HasForeignKey("ProgramsProgramName");

                    b.HasOne("EnrollmentApp.Student", null)
                        .WithMany("RegistredCourses")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("EnrollmentApp.Student", b =>
                {
                    b.HasOne("EnrollmentApp.Programs", "program")
                        .WithMany()
                        .HasForeignKey("ProgramNames")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnrollmentApp.Programs", null)
                        .WithMany("RegisredStudentsList")
                        .HasForeignKey("ProgramsProgramName");

                    b.HasOne("EnrollmentApp.Course", "courses")
                        .WithMany()
                        .HasForeignKey("courseCode");
                });
#pragma warning restore 612, 618
        }
    }
}
